Prerna/user login page2
DataBytes-Organisation/DiscountMate_new pull request #32
Opened 2024-09-04 14:03 UTC by prshah94

Updated the profile page to allow profile image selection. Need to connect to back end later

2024-09-16 09:33 UTC, rvklenora requested changes
<Text style={styles.infoText}>Location: Australia</Text>
            <Text style={styles.infoText}>Member since: January 1, 2024</Text>
            <Text style={styles.infoText}>Biography: 40 year old man looking for discounts for family of 4</Text>


I like the overall frontend design of this page. But, does this implementation pull the user data from the backend? If you look at the profile.tsx implementation in main I use a get request to retrieve all user information.

2024-09-17 06:30 UTC, NathanNguyen-Dev commented
There is another conflict with this can someone have a look from web and possible rebase all these to the correct version @benD02  @rvklenora

2024-09-17 13:00 UTC, prshah94 commented
@rvklenora Okay I'll make a new branch that has your set up and try to integrate this code.

2024-09-18 02:48 UTC, prshah94 commented
I'm closing this Pull request because I made the change 'pull the user data from the backend' in a new pull request.

2024-09-18 02:48 UTC, closed without merging