Asma/discussion page
DataBytes-Organisation/DiscountMate_new pull request #42
Opened 2024-09-15 11:59 UTC by AsmaStudyAccount

Refractor Backend code so cleaner and now scalable if more data need backend

2024-09-16 05:49 UTC, benD02 approved these changes

2024-09-16 09:35 UTC, rvklenora reviewed
Testing this right now, will let you know how I go. Thanks for the refactor :)

2024-09-16 10:13 UTC, rvklenora requested changes
Contact us page providing me a 404 upon testing. Soon as this is fixed this should be ready to merge. All other features working perfectly. If you find it easier to test you can setup nodemailer to the mongodb email which is shared. Private messaged you on teams with a screenshot of the error.

2024-09-17 06:29 UTC, NathanNguyen-Dev commented
There is a file conflict can somebody resolve this on web team @benD02  @rvklenora

2024-09-19 12:24 UTC, closed without merging