Added Context based Recommendation using BERT
DataBytes-Organisation/DiscountMate_new pull request #87
Opened 2024-12-12 01:53 UTC by Screwlogist

Added Context based Recommendation using BERT. Will add other model one by one.

2024-12-12 10:41 UTC, rashannon-sys requested changes
Please add in comments explaining what each part of the code is doing, thanks

2024-12-12 22:16 UTC, Screwlogist commented
Hey Riley,

Added more comments.

2024-12-13 02:39 UTC, Screwlogist commented
Added Personalization based recommendation system.

2024-12-14 12:26 UTC, rashannon-sys approved these changes

2024-12-14 12:26 UTC, merged